defaults: &defaults
  docker:
    - image: circleci/node:12
      environment:
        ## this enables colors in the output
        TERM: xterm
version: 2.1
jobs:
  deploy-code:
    << : *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
            - v3-deps-{{ .Branch }}-
            - v3-deps-
      - run:
          name: Install tooling
          command: |
            sudo apt-get -y -qq install awscli dnsutils
            sudo npm install -g pnpm
            sudo npm install -g serverless@1.83.3
      - run:
          name: Install dependencies
          command: |
            pnpm install
            sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - save_cache:
          key: v3-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/project/node_modules
            - ~/.cache
      - run:
          name: pnpm run lint
          command: |
            cd ~/project/solution/ui
            pnpm run lint
      - run:
          name: Run test
          command: |
            cd ~/project/solution/ui
            pnpm run test
      - run: 
          name: Run cypress test
          command: | 
            cd ~/project/solution/ui
            sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            pnpm install
            pnpm run cy-server-test
      - store_artifacts:
              path: solution/ui/cypress/videos
      - store_artifacts:
              path: solution/ui/cypress/screenshots
      - deploy:
          name: Deploy the code
          requires:
            Install dependencies
          command: |
             serverless config credentials --provider aws --profile SBA-lower --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
             cd scripts
             if [[ "master" == "${CIRCLE_BRANCH}" ]]; 
               then export TARGET="staging";
             else export TARGET="${CIRCLE_USERNAME}"; fi
             source ./environment-deploy.sh ${TARGET}

workflows:
  version: 2.1
  build:
    jobs:
      - deploy-code:
          context: sba-gov-bepcalc
