defaults: &defaults
  docker:
    - image: circleci/node:12
      environment:
        ## this enables colors in the output
        TERM: xterm
version: 2.1
jobs:
  lint-frontend:
    << : *defaults
    steps:
      - checkout
      - run:
          command: |
            cd ~/project/solution/ui
            npm run lint
  deploy-code:
    << : *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: Install tooling
          command: |
            sudo apt-get -y -qq install awscli dnsutils libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            sudo npm install -g pnpm
            sudo npm install -g serverless
      - run:
          name: Install dependencies
          command: |
            pnpm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Deploy the code
          requires:
            Install dependencies
          command: |
             serverless config credentials --provider aws --profile lower --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
             cd solution/ui
             gatsby build
             cd ../../scripts
             source ./environment-deploy.sh ${CIRCLE_USERNAME}
      - run:
          name: Run Tests
          requires:
            Deploy the code
          command: |
            serverless config credentials --provider aws --profile lower --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            cd scripts
            source ./get-info.sh ${CIRCLE_USERNAME}
            cd ../solution/ui
            pnpm run test 


workflows:
  version: 2.1
  build:
    jobs:
      - lint-frontend
      - deploy-code:
          context: bec
          requires:
            - lint-frontend
