regionShortNamesMap:
  "us-east-2": "oh"
  "us-east-1": "va"
  "us-west-1": "ca"
  "us-west-2": "or"
  "ap-east-1": "hk"
  "ap-south-1": "mum"
  "ap-northeast-3": "osa"
  "ap-northeast-2": "sel"
  "ap-southeast-1": "sg"
  "ap-southeast-2": "syd"
  "ap-northeast-1": "ty"
  "ca-central-1": "ca"
  "cn-north-1": "cn"
  "cn-northwest-1": "nx"
  "eu-central-1": "fr"
  "eu-west-1": "irl"
  "eu-west-2": "ldn"
  "eu-west-3": "par"
  "eu-north-1": "sth"
  "me-south-1": "bhr"
  "sa-east-1": "sao"
  "us-gov-east-1": "gce"
  "us-gov-west-1": "gcw"

# The default region to deploy to
awsRegion: us-east-1

# Short region name
# This is used in the namespace to avoid naming collisions to allow deploying the same solution across multiple regions
# Currently using the ISO country code or state code or city abbreviation as short name of the region
# See "regionShortNamesMap" defined above.
# The above mapping needs to be updated when deploying to any region other than the ones listed above in future
awsRegionShortName: ${self:custom.settings.regionShortNamesMap.${self:custom.settings.awsRegion}}

# This prefix is used for naming various resources
namespace: ${self:custom.settings.envName}-${self:custom.settings.awsRegionShortName}-${self:custom.settings.solutionName}

# This is the namespace for naming resources that have global namespace such as S3 bucket names
globalNamespace: ${self:custom.settings.awsAccountInfo.awsAccountId}-${self:custom.settings.namespace}

# Name of the deployment bucket. The serverless framework uploads various artifacts to this bucket.
# These artifacts include things like Lambda function code ZIP files, AWS CloudFormation Templates etc
deploymentBucketName: ${self:custom.settings.globalNamespace}-artifacts

# Root path in parameter store for parameters used by this solution.
paramStoreRoot: "${self:custom.settings.envName}/${self:custom.settings.solutionName}"

